### ISSUE TITLE
Submit Review after uploading

### ISSUE THREAD

**Issue by cosic** [Litres/samsung-publisher-gradle-plugin#4]
## ⚠️ Is your feature request related to a problem? Please describe
I need to send a build for review immediately after uploading a file. Now by default after using the plugin you need to manually go to the console and click the «Submit» button.

## 💡 Describe the solution you'd like
Add extension plugin parameter to control submit review action. Use API https://developer.samsung.com/galaxy-store/galaxy-store-developer-api/content-publish-api/submit-app.html 

## 🤚 Do you want to develop this feature yourself?
- [x] Yes
- [ ] No

**Comment by Toxa2033** [comment]
Released new version 0.0.5 with this changes
